-- =====================================================================
-- LabResultados — Esquema de base de datos (PostgreSQL)
-- Trabajo Final Integrador · Grupo 111 · UTN
--
-- Script de creación del esquema relacional.
-- Orden de ejecución: 01_schema.sql → 02_datos_prueba.sql
-- Requiere PostgreSQL 12 o superior (usa columnas generadas).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0. Reinicio del esquema (solo desarrollo)
--    Permite volver a ejecutar el script desde cero.
--    NO ejecutar sobre una base con datos reales.
-- ---------------------------------------------------------------------
DROP VIEW  IF EXISTS vista_historial_resultados;
DROP TABLE IF EXISTS notificacion, resultado, orden_estudio, orden,
                     rango_referencia, analito, estudio,
                     paciente, obra_social, usuario, rol CASCADE;


-- =====================================================================
-- 1. TABLAS
--    Agrupadas según el módulo que las administra (ver docs/modulos.md).
-- =====================================================================

-- ---------------------------------------------------------------------
-- Módulo: Gestión de usuarios y roles
-- ---------------------------------------------------------------------
CREATE TABLE rol (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre  VARCHAR(30) NOT NULL UNIQUE          -- ADMINISTRADOR, RECEPCION, BIOQUIMICO
);

CREATE TABLE usuario (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol_id         BIGINT       NOT NULL,
    nombre         VARCHAR(60)  NOT NULL,
    apellido       VARCHAR(60)  NOT NULL,
    email          VARCHAR(120) NOT NULL UNIQUE,  -- se usa para iniciar sesión
    password_hash  VARCHAR(255) NOT NULL,         -- hash BCrypt, nunca la contraseña en texto plano
    activo         BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_alta     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- Módulo: Gestión de pacientes
-- ---------------------------------------------------------------------
CREATE TABLE obra_social (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre  VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE paciente (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    obra_social_id    BIGINT,                      -- cobertura actual; NULL = particular
    dni               VARCHAR(8)   NOT NULL UNIQUE,
    nombre            VARCHAR(60)  NOT NULL,
    apellido          VARCHAR(60)  NOT NULL,
    fecha_nacimiento  DATE         NOT NULL,       -- necesaria para elegir el rango de referencia
    sexo              CHAR(1)      NOT NULL,       -- necesario para elegir el rango de referencia
    email             VARCHAR(120),                -- destino de las notificaciones
    telefono          VARCHAR(30),
    nro_afiliado      VARCHAR(30),
    fecha_alta        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_paciente_dni  CHECK (dni ~ '^[0-9]{7,8}$'),
    CONSTRAINT ck_paciente_sexo CHECK (sexo IN ('F', 'M', 'X'))   -- X: DNI no binario
);

-- ---------------------------------------------------------------------
-- Módulo: Administración de estudios
-- ---------------------------------------------------------------------
CREATE TABLE estudio (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(100) NOT NULL UNIQUE,     -- ej.: Hemograma, Perfil lipídico
    descripcion  VARCHAR(255),
    activo       BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE analito (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudio_id  BIGINT       NOT NULL,
    nombre      VARCHAR(100) NOT NULL,             -- ej.: Glucosa, Colesterol total
    unidad      VARCHAR(20)  NOT NULL,             -- ej.: mg/dL, g/dL
    CONSTRAINT uq_analito_estudio_nombre UNIQUE (estudio_id, nombre)
);

-- Un analito puede tener varios rangos (ej.: la hemoglobina normal
-- es distinta en hombres y mujeres). Las columnas en NULL significan
-- "sin restricción" (aplica a ambos sexos / cualquier edad / sin tope).
CREATE TABLE rango_referencia (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analito_id  BIGINT        NOT NULL,
    sexo        CHAR(1),
    edad_min    SMALLINT,                          -- en años
    edad_max    SMALLINT,                          -- en años
    valor_min   NUMERIC(12,4),
    valor_max   NUMERIC(12,4),
    CONSTRAINT ck_rango_sexo    CHECK (sexo IS NULL OR sexo IN ('F', 'M')),
    CONSTRAINT ck_rango_edades  CHECK (edad_min IS NULL OR edad_max IS NULL OR edad_min <= edad_max),
    CONSTRAINT ck_rango_valores CHECK (valor_min IS NOT NULL OR valor_max IS NOT NULL),
    CONSTRAINT ck_rango_orden   CHECK (valor_min IS NULL OR valor_max IS NULL OR valor_min <= valor_max)
);

-- ---------------------------------------------------------------------
-- Módulo: Gestión de órdenes
-- ---------------------------------------------------------------------
CREATE TABLE orden (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(20)  NOT NULL UNIQUE,  -- el paciente lo usa (junto con su DNI) para consultar
    paciente_id     BIGINT       NOT NULL,
    obra_social_id  BIGINT,                        -- cobertura usada en ESTA orden
    creada_por      BIGINT       NOT NULL,         -- usuario de recepción que la registró
    estado          VARCHAR(12)  NOT NULL DEFAULT 'EN_PROCESO',
    fecha_creacion  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    fecha_listo     TIMESTAMPTZ,                   -- cuándo pasó a LISTO
    fecha_entrega   TIMESTAMPTZ,                   -- cuándo pasó a ENTREGADO
    CONSTRAINT ck_orden_estado CHECK (estado IN ('EN_PROCESO', 'LISTO', 'ENTREGADO'))
);

-- Tabla intermedia: qué estudios se pidieron en cada orden.
-- Resuelve la relación N:M entre orden y estudio.
CREATE TABLE orden_estudio (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id    BIGINT NOT NULL,
    estudio_id  BIGINT NOT NULL,
    CONSTRAINT uq_orden_estudio UNIQUE (orden_id, estudio_id)
);

-- ---------------------------------------------------------------------
-- Módulo: Gestión de resultados
-- ---------------------------------------------------------------------
CREATE TABLE resultado (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_estudio_id  BIGINT         NOT NULL,
    analito_id        BIGINT         NOT NULL,
    cargado_por       BIGINT         NOT NULL,     -- bioquímico que cargó el valor
    valor             NUMERIC(12,4)  NOT NULL,
    -- Copia de la unidad y del rango vigentes al momento de la carga:
    -- el resultado se sigue interpretando igual aunque después cambie
    -- la configuración del estudio (regla del módulo Historial).
    unidad            VARCHAR(20)    NOT NULL,
    ref_min           NUMERIC(12,4),
    ref_max           NUMERIC(12,4),
    -- Lo calcula la propia base: TRUE si el valor cae fuera del rango.
    fuera_de_rango    BOOLEAN GENERATED ALWAYS AS (
                          (ref_min IS NOT NULL AND valor < ref_min) OR
                          (ref_max IS NOT NULL AND valor > ref_max)
                      ) STORED,
    observacion       VARCHAR(255),
    fecha_carga       TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT uq_resultado_analito UNIQUE (orden_estudio_id, analito_id)
);

-- ---------------------------------------------------------------------
-- Módulo: Notificaciones
-- ---------------------------------------------------------------------
CREATE TABLE notificacion (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id        BIGINT       NOT NULL,
    email_destino   VARCHAR(120) NOT NULL,
    estado          VARCHAR(10)  NOT NULL DEFAULT 'PENDIENTE',
    fecha_creacion  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    fecha_envio     TIMESTAMPTZ,
    detalle         VARCHAR(255),                  -- ej.: motivo de un envío fallido
    CONSTRAINT ck_notificacion_estado CHECK (estado IN ('PENDIENTE', 'ENVIADA', 'FALLIDA'))
);


-- =====================================================================
-- 2. RELACIONES (claves foráneas)
--    Todas son N:1 (muchos → uno): la flecha va desde la tabla que
--    tiene la clave foránea hacia la tabla referenciada.
--    Ver el diagrama en database/diagrama-er.md
-- =====================================================================

-- usuario (N) → (1) rol: cada usuario tiene un único rol
ALTER TABLE usuario
    ADD CONSTRAINT fk_usuario_rol
    FOREIGN KEY (rol_id) REFERENCES rol (id);

-- paciente (N) → (1) obra_social: cobertura actual del paciente (opcional)
ALTER TABLE paciente
    ADD CONSTRAINT fk_paciente_obra_social
    FOREIGN KEY (obra_social_id) REFERENCES obra_social (id);

-- analito (N) → (1) estudio: un estudio se compone de uno o más analitos
ALTER TABLE analito
    ADD CONSTRAINT fk_analito_estudio
    FOREIGN KEY (estudio_id) REFERENCES estudio (id);

-- rango_referencia (N) → (1) analito: un analito puede tener varios rangos
-- (si se borra el analito, sus rangos se borran con él)
ALTER TABLE rango_referencia
    ADD CONSTRAINT fk_rango_analito
    FOREIGN KEY (analito_id) REFERENCES analito (id) ON DELETE CASCADE;

-- orden (N) → (1) paciente: un paciente puede tener muchas órdenes
ALTER TABLE orden
    ADD CONSTRAINT fk_orden_paciente
    FOREIGN KEY (paciente_id) REFERENCES paciente (id);

-- orden (N) → (1) obra_social: cobertura usada en la orden (opcional)
ALTER TABLE orden
    ADD CONSTRAINT fk_orden_obra_social
    FOREIGN KEY (obra_social_id) REFERENCES obra_social (id);

-- orden (N) → (1) usuario: quién registró la orden
ALTER TABLE orden
    ADD CONSTRAINT fk_orden_usuario
    FOREIGN KEY (creada_por) REFERENCES usuario (id);

-- orden_estudio (N) → (1) orden    } juntas resuelven la relación
-- orden_estudio (N) → (1) estudio  } N:M entre orden y estudio
ALTER TABLE orden_estudio
    ADD CONSTRAINT fk_orden_estudio_orden
    FOREIGN KEY (orden_id) REFERENCES orden (id) ON DELETE CASCADE;

ALTER TABLE orden_estudio
    ADD CONSTRAINT fk_orden_estudio_estudio
    FOREIGN KEY (estudio_id) REFERENCES estudio (id);

-- resultado (N) → (1) orden_estudio: el resultado pertenece a un estudio pedido en la orden
-- (sin CASCADE a propósito: una orden que ya tiene resultados NO se puede borrar)
ALTER TABLE resultado
    ADD CONSTRAINT fk_resultado_orden_estudio
    FOREIGN KEY (orden_estudio_id) REFERENCES orden_estudio (id);

-- resultado (N) → (1) analito: qué se midió
ALTER TABLE resultado
    ADD CONSTRAINT fk_resultado_analito
    FOREIGN KEY (analito_id) REFERENCES analito (id);

-- resultado (N) → (1) usuario: bioquímico que cargó el resultado
ALTER TABLE resultado
    ADD CONSTRAINT fk_resultado_usuario
    FOREIGN KEY (cargado_por) REFERENCES usuario (id);

-- notificacion (N) → (1) orden: registro de los avisos enviados por cada orden
ALTER TABLE notificacion
    ADD CONSTRAINT fk_notificacion_orden
    FOREIGN KEY (orden_id) REFERENCES orden (id);


-- =====================================================================
-- 3. ÍNDICES
--    PostgreSQL no indexa automáticamente las claves foráneas. Se crean
--    índices en las columnas que más se usan para buscar y unir tablas.
--    (Las columnas UNIQUE —dni, codigo, email— ya tienen índice propio.)
-- =====================================================================
CREATE INDEX ix_orden_paciente         ON orden (paciente_id);       -- órdenes de un paciente
CREATE INDEX ix_orden_estado           ON orden (estado);            -- órdenes pendientes de resultados
CREATE INDEX ix_orden_estudio_estudio  ON orden_estudio (estudio_id);
CREATE INDEX ix_analito_estudio        ON analito (estudio_id);
CREATE INDEX ix_rango_analito          ON rango_referencia (analito_id);
CREATE INDEX ix_resultado_analito      ON resultado (analito_id);    -- historial de un analito
CREATE INDEX ix_notificacion_orden     ON notificacion (orden_id);


-- =====================================================================
-- 4. VISTA: historial de resultados del paciente
--    Une paciente → orden → estudio → resultado → analito en una sola
--    consulta. La usa el módulo "Historial de resultados" para mostrar
--    la evolución de un analito en el tiempo (ej.: la glucosa de las
--    últimas órdenes del paciente).
--    Solo incluye órdenes LISTO o ENTREGADO: una orden EN_PROCESO no
--    debe mostrarle resultados al paciente (regla del módulo Consulta).
-- =====================================================================
CREATE VIEW vista_historial_resultados AS
SELECT
    p.id              AS paciente_id,
    p.dni,
    o.codigo          AS codigo_orden,
    o.fecha_creacion  AS fecha_orden,
    o.estado          AS estado_orden,
    e.nombre          AS estudio,
    a.id              AS analito_id,
    a.nombre          AS analito,
    r.valor,
    r.unidad,
    r.ref_min,
    r.ref_max,
    r.fuera_de_rango
FROM resultado r
JOIN orden_estudio oe ON oe.id = r.orden_estudio_id
JOIN orden         o  ON o.id  = oe.orden_id
JOIN paciente      p  ON p.id  = o.paciente_id
JOIN estudio       e  ON e.id  = oe.estudio_id
JOIN analito       a  ON a.id  = r.analito_id
WHERE o.estado IN ('LISTO', 'ENTREGADO');
