-- =====================================================================
-- LabResultados — Esquema de base de datos (PostgreSQL)
-- Trabajo Final Integrador · Grupo 111 · UTN
--
-- Script de creación del esquema relacional.
-- Orden de ejecución: 01_schema.sql → 02_datos_prueba.sql
-- Requiere PostgreSQL 12 o superior (usa columnas generadas).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0. Reinicio del esquema (solo desarrollo)
--    Permite volver a ejecutar el script desde cero.
--    NO ejecutar sobre una base con datos reales.
-- ---------------------------------------------------------------------
DROP VIEW  IF EXISTS vista_historial_resultados;
DROP TABLE IF EXISTS notificacion, resultado, orden_estudio, orden,
                     rango_referencia, analito, estudio,
                     paciente, obra_social, usuario, rol CASCADE;


-- =====================================================================
-- 1. TABLAS
--    Agrupadas según el módulo que las administra (ver docs/modulos.md).
-- =====================================================================

-- ---------------------------------------------------------------------
-- Módulo: Gestión de usuarios y roles
-- ---------------------------------------------------------------------
CREATE TABLE rol (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre  VARCHAR(30) NOT NULL UNIQUE          -- ADMINISTRADOR, RECEPCION, BIOQUIMICO
);

CREATE TABLE usuario (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol_id         BIGINT       NOT NULL,
    nombre         VARCHAR(60)  NOT NULL,
    apellido       VARCHAR(60)  NOT NULL,
    email          VARCHAR(120) NOT NULL UNIQUE,  -- se usa para iniciar sesión
    password_hash  VARCHAR(255) NOT NULL,         -- hash BCrypt, nunca la contraseña en texto plano
    activo         BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_alta     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- Módulo: Gestión de pacientes
-- ---------------------------------------------------------------------
CREATE TABLE obra_social (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre  VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE paciente (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    obra_social_id    BIGINT,                      -- cobertura actual; NULL = particular
    dni               VARCHAR(8)   NOT NULL UNIQUE,
    nombre            VARCHAR(60)  NOT NULL,
    apellido          VARCHAR(60)  NOT NULL,
    fecha_nacimiento  DATE         NOT NULL,       -- necesaria para elegir el rango de referencia
    sexo              CHAR(1)      NOT NULL,       -- necesario para elegir el rango de referencia
    email             VARCHAR(120),                -- destino de las notificaciones
    telefono          VARCHAR(30),
    nro_afiliado      VARCHAR(30),
    fecha_alta        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_paciente_dni  CHECK (dni ~ '^[0-9]{7,8}$'),
    CONSTRAINT ck_paciente_sexo CHECK (sexo IN ('F', 'M', 'X'))   -- X: DNI no binario
);

-- ---------------------------------------------------------------------
-- Módulo: Administración de estudios
-- ---------------------------------------------------------------------
CREATE TABLE estudio (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(100) NOT NULL UNIQUE,     -- ej.: Hemograma, Perfil lipídico
    descripcion  VARCHAR(255),
    activo       BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE analito (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudio_id  BIGINT       NOT NULL,
    nombre      VARCHAR(100) NOT NULL,             -- ej.: Glucosa, Colesterol total
    unidad      VARCHAR(20)  NOT NULL,             -- ej.: mg/dL, g/dL
    CONSTRAINT uq_analito_estudio_nombre UNIQUE (estudio_id, nombre)
);

-- Un analito puede tener varios rangos (ej.: la hemoglobina normal
-- es distinta en hombres y mujeres). Las columnas en NULL significan
-- "sin restricción" (aplica a ambos sexos / cualquier edad / sin tope).
CREATE TABLE rango_referencia (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analito_id  BIGINT        NOT NULL,
    sexo        CHAR(1),
    edad_min    SMALLINT,                          -- en años
    edad_max    SMALLINT,                          -- en años
    valor_min   NUMERIC(12,4),
    valor_max   NUMERIC(12,4),
    CONSTRAINT ck_rango_sexo    CHECK (sexo IS NULL OR sexo IN ('F', 'M')),
    CONSTRAINT ck_rango_edades  CHECK (edad_min IS NULL OR edad_max IS NULL OR edad_min <= edad_max),
    CONSTRAINT ck_rango_valores CHECK (valor_min IS NOT NULL OR valor_max IS NOT NULL),
    CONSTRAINT ck_rango_orden   CHECK (valor_min IS NULL OR valor_max IS NULL OR valor_min <= valor_max)
);

-- ---------------------------------------------------------------------
-- Módulo: Gestión de órdenes
-- ---------------------------------------------------------------------
CREATE TABLE orden (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(20)  NOT NULL UNIQUE,  -- el paciente lo usa (junto con su DNI) para consultar
    paciente_id     BIGINT       NOT NULL,
    obra_social_id  BIGINT,                        -- cobertura usada en ESTA orden
    creada_por      BIGINT       NOT NULL,         -- usuario de recepción que la registró
    estado          VARCHAR(12)  NOT NULL DEFAULT 'EN_PROCESO',
    fecha_creacion  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    fecha_listo     TIMESTAMPTZ,                   -- cuándo pasó a LISTO
    fecha_entrega   TIMESTAMPTZ,                   -- cuándo pasó a ENTREGADO
    CONSTRAINT ck_orden_estado CHECK (estado IN ('EN_PROCESO', 'LISTO', 'ENTREGADO'))
);

-- Tabla intermedia: qué estudios se pidieron en cada orden.
-- Resuelve la relación N:M entre orden y estudio.
CREATE TABLE orden_estudio (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id    BIGINT NOT NULL,
    estudio_id  BIGINT NOT NULL,
    CONSTRAINT uq_orden_estudio UNIQUE (orden_id, estudio_id)
);

-- ---------------------------------------------------------------------
-- Módulo: Gestión de resultados
-- ---------------------------------------------------------------------
CREATE TABLE resultado (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_estudio_id  BIGINT         NOT NULL,
    analito_id        BIGINT         NOT NULL,
    cargado_por       BIGINT         NOT NULL,     -- bioquímico que cargó el valor
    valor             NUMERIC(12,4)  NOT NULL,
    -- Copia de la unidad y del rango vigentes al momento de la carga:
    -- el resultado se sigue interpretando igual aunque después cambie
    -- la configuración del estudio (regla del módulo Historial).
    unidad            VARCHAR(20)    NOT NULL,
    ref_min           NUMERIC(12,4),
    ref_max           NUMERIC(12,4),
    -- Lo calcula la propia base: TRUE si el valor cae fuera del rango.
    fuera_de_rango    BOOLEAN GENERATED ALWAYS AS (
                          (ref_min IS NOT NULL AND valor < ref_min) OR
                          (ref_max IS NOT NULL AND valor > ref_max)
                      ) STORED,
    observacion       VARCHAR(255),
    fecha_carga       TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT uq_resultado_analito UNIQUE (orden_estudio_id, analito_id)
);

-- ---------------------------------------------------------------------
-- Módulo: Notificaciones
-- ---------------------------------------------------------------------
CREATE TABLE notificacion (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id        BIGINT       NOT NULL,
    email_destino   VARCHAR(120) NOT NULL,
    estado          VARCHAR(10)  NOT NULL DEFAULT 'PENDIENTE',
    fecha_creacion  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    fecha_envio     TIMESTAMPTZ,
    detalle         VARCHAR(255),                  -- ej.: motivo de un envío fallido
    CONSTRAINT ck_notificacion_estado CHECK (estado IN ('PENDIENTE', 'ENVIADA', 'FALLIDA'))
);
